# Generated by Django 3.1.7 on 2021-05-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
