# Generated by Django 3.1.7 on 2021-05-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
    ]
