# Generated by Django 3.1.7 on 2021-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210417_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
